services:
  - type: web
    name: fitness-tracker
    env: node
    plan: free
    buildCommand: ""
    startCommand: "node server.js"
    envVars:
      - key: NODE_ENV
        value: production
